local my_language = {
	give_vehicle = "Hai aggiunto ~b~%s~w~ al tuo inventario.",
	store_vehicle_command = "Parcheggia il veicolo che stai guidando",
	no_entity_vehicle = "~r~Il veicolo non esiste oppure è troppo lontano da te.",
	no_entity_vehicle_id = "~r~Il veicolo non è vincolato a nessuno, quindi non puoi prendertelo ( Bug ).",
	store_vehicle = "~b~Hai messo via il tuo veicolo.",
	teleported_former_position = "~g~Sei stato teletrasportato alla tua ultima posizione salvata.",
	not_enough_of = "~r~Non hai abbastanza %s.",
	max_storage_chest = "~r~La cassa è piena.",
	cant_carry_more_items = "~r~Il tuo inventario è pieno.",
	put_item = "Hai messo ~g~x%s~w~ %s~w~.",
	take_item = "Hai preso ~g~x%s~w~ %s~w~.",
	delete_item = "Hai rimosso ~r~x%s~w~ %s~w~.",
	you_equiped_item = "Hai equipaggiato ~g~%s~w~.",
	bind_weapon_command = "Scorciatoia per slot per armi %s",
	kevlar_broke = "~r~AHH!~n~~w~La tua armatura è rotta.",
	inventory_command = "Rimozione forzata dell\'inventario",
	press_enter_to_join = "Premi ~g~INVIO~w~ per iniziare a giocare.",
	new_character = "Nuovo personaggio",
	survivor = "Sopravissuto",
	right = "Destra",
	left = "Sinistra",
	male = "Maschio",
	female = "Femmina",
	ped = "Ped",
	name = "Nome",
	sex = "Sesso",
	title = "Titolo",
	select_this_character = "Seleziona questo personaggio",
	no_entity_zombie = "Lo Zombie non esiste oppure è troppo lontano da te.",
	you_found = "Hai trovato ~g~%sx %s~w~.",
	you_found_nothing = "Non hai trovato ~g~Niente~w~.",
	press_e_to_loot = "Premi ~b~[E]~w~ per Lootare",
	full_for_item = "~r~Non hai abbastanza spazio per questo item.",
	put_item_container = "Hai messo ~g~x%s~w~ %s~w~ in your container.",
	take_item_container = "Hai preso ~g~x%s~w~ %s~w~ from your container.",
	not_allowed_here = "~r~Non hai il permesso di farlo qui.",
	cant_store_moving_veh = "~r~Non puoi parcheggiare un veicolo in movimento.",
	use_repair_tool = "Usa il kit di riparazione",
	please_get_closer = "~b~Avvicinati, non ci sono entità nelle vicinanze.",
	you_cancel_action = "~r~Hai cancellato l'azione.",
	selected_target_message = "Target selezionato:~n~%s~n~~r~premi ~b~Y~r~ per annullare~n~~r~premi ~g~X~r~ per continuare.",
	target_you = "~b~TU",
	target_screen = "~g~Visualizzato",
	take_this_path = "Prendi questa strada",

	-- hud
	default_hud = "HUD Predefinito",
	cinema_hud = "HUD Cinematografico",
	no_hud = "Senza HUD",

	-- perms
	kick_member = "Espelli Membri",
	invite_someone = "Invita Membri",
	edit_member = "Modifica Membri",
	edit_rank = "Modifica Rank",
	create_rank = "Crea Rank",
	delete_rank = "Elimina Rank",
	edit_structure = "Modifica Info Della Crew",
	edit_permissions = "Modifica Permessi",
	permission_level = "Permission grant",
	red_delete = "Elimina",
	rank = "Rank",
	red_kick = "Espelli",
	crew_name = "Nome della crew",
	slogan = "Motto Della Crew",
	information = "Informazioni",
	boss_rank = "Nome rank del Boss",
	member_rank = "Nome rank Membri",
	member = "Membri",

	permissions_manager = "Gestione Rank",
	members_manager = "Gestisci Membri",
	ranks_manager = "Gestisci Rank",
	ranks_list = "Lista Rank",
	members_list = "Lista Membri",
	create_a_rank = "Crea Un Rank",
	invite_someone = "Invita Qualcuno",
	stats = "Statistiche",
	total_ranks = "Rank Totali",
	total_members = "Membri Totali",
	level = "Livelli",
	actions = "Azioni",
	crew_manager = "Gestisci Crew",
	you_created_a_new_crew = "Hai creato una nuova crew: %s",
	you_deleted_your_crew = "Hai eliminato la tua crew.",
	you_are_not_in_a_crew = "Non sei in una crew",
	you_joined_the_crew = "Sei entrato in una nuova crew '%s'",
	kick_failed = "Espulsione fallita, ragione: %s",
	already_in_crew = "Sei già in una crew",
	no_invitation = "Non hai ricevuto nessun invito.",
	left_crew = "Hai lasciato la crew.",
	permission_updated = "I permessi per <C>~g~%s</C>~w~ sono stati aggiornati.",
	incorrect_name = "~r~Il formato del nome è sbagliato",
	incorrect_rank_perm = "~r~Errore\n~w~Il nome del rank o il livello di permesso è invalido.",
	warn_rank_limit = "~r~Sei arrivato al rank massimo.",
	create_rank_success = "~g~Successo\n~w~Hai creato un nuovo rank <C>~b~%s</C>~w~ con il livello di permesso di <C>~b~%s</C>~w~.",
	crew_grant_warn = "~HUD_COLOUR_DEGEN_RED~Non puoi interagire con un membro che ha il livello di permesso superiore al tuo.",
	you_sent_an_invitation = "Hai mandato un invito <C>~g~%s</C>~w~ per farlo entrare nella tua crew.",
	you_received_an_invitation = "Hai ricevuto un invito per entrare in una crew.\nfai ~b~/%s per accettare.",
	invitation_expired = "L\'invito è scaduto",
	crew_kick_success = "Hai espulso <C>~b~%s</C>~w~ dalla crew.",
	first_rank_warning = "Il primo rank è quello 'predefinito'.",

	you_updated_this = "Hai aggiornato %s a ~g~<C>%s</C>~w~.",
	changes_saved_on = "Il cambiamento su <C>~g~%s</C>~w~ è stato salvato.",
	yes = "si",
	no = "no",
	none = "None",
	character_id = "ID Personaggio",
	server_id = "ID Server",
	report = "Reporta",
	rename = "Rinomina",
	trade_with = "Scambia",

	-- cloth
	take_outfit = "Compra questo outfit",
	wardrobe_options = "Impostazioni guardaroba",
	wardrobe = "Guardaroba",
	manual_options = "Opzioni manuali",
	manual_mode = "Modalità manuale",
	save_outfit = "Salva questo outfit",
	variation = "Variazioni",
	outfits = "outfits",
	cloth_shop = "Negozio Di Vestiti",
	ped_cloth_shop = "Negozio Di Vestiti Per PED",
	manual_props = "Props manuali",
	manuel = "manuali",
	new_name = "Nuovo Nome",
	outfit_name = "Nome Del''Outfit",
	variations_saved = "~g~Successo.~n~~w~le variazioni al tuo personaggio sono state salvate.",
	equipped_new_outfit = "Hai equipaggiato il tuo nuovo outfit: ~b~%s",
	warning_limit_outfits = "Hai raggiunto il massimo di outfit che puoi salvare. ~g~(%s)",
	saved_new_outfit = "Hai salvato un nuovo outfit: ~b~%s~w~.",
	rename_outfit = "Il tuo outfit ~b~%s~w~ è stato rinominato come ~g~%s~w~.",
	delete_outfit = "Il tuo outfit: ~b~%s~w~ è stato cancellato.",

	torso = "Torso",
	props = "Props",
	top = "Top",
	tops = "Tops",
	badge = "Badge",
	pants = "Pantaloni",
	pant = "Pant",
	shoes = "Scarpe",
	bags = "Borsoni",
	undershirt = "Canottiera",
	neck = "Catene",
	bracelets = "bracelets",
	montres = "Orologi",
	earrings = "Orecchini",
	glasses = "Occhiali",
	hats = "Cappelli",
	graphiques = "Decorazioni",

	-- health
	inconscious = "Incosciente",
	doing_something = "Facendo qualcosa",
	time_before_respawn = "Tempo prima del respawn",
	you_died = "~r~Sei morto.",
	healing_wounds = "Curando le ferite",
	already_doing_something = "~r~Stai gia facendo qualcos'altro.",
	you_have_been_healed = "~g~Sei stato curato.",
	you_respawned = "~g~Sei respawnato.",

	player_too_far_to_interact = "~r~Il giocatore con cui vuoi interagire è troppo lontano da te.",
	send_trade_invitation_to = "Hai mandato un invito per uno scambio a ~b~%s~w~.\n~b~Aspetta che il giocatore accetti.",
	receive_invitation_from = "Hai ricevuto un invito per uno scambio da ~b~%s~w~.\n~b~Scrivi ~w~/trade accept %s~b~ per iniziare lo scambio.",

	invalid_command_args = "Argomenti del comando non validi: %s",
	start_trade_command_help = "Inizia uno scambio con un'altro giocatore",
	accept_trade_command_help = "Accetta l'invito per lo scambio",
	deny_trade_command_help = "Nega l'invito per lo scambio",
	invalid_invitation = "L'invito non è valido oppure è scaduto",
	name_accepted_your_trade_invitation = "~b~%s~w~ Ha accettato l'invito per lo scambio ricevuto",
	you_accepted_trade_invitation_of_name = "Hai accettato l'invito per lo scambio ricevuto da %s",
	name_denied_your_trade_invitation = "~b~%s~w~ ha rifiutato l'invito per lo scambio",
	you_denied_trade_invitation_of_name = "Hai rifiutato l'invito per lo scambio ricevuto da %s",
	you_already_trading = "Stai già facendo uno scambio",
	other_already_trading = "L'altro giocatore stà gia facendo uno scambio",

	other_player_not_enough_money = "~r~Lo scambio è fallito. L'altro giocatore non aveva abbastanza soldi.",
	you_player_not_enough_money = "~r~Lo scambio è fallito. Non hai abbastanza soldi.",
	other_player_not_enough_item = "~r~Lo scambio è fallito. L'altro giocatore non aveva abbastanza di alcuni oggetti.",
	you_player_not_enough_item = "~r~Lo scambio è fallito. Non avevi abbastanza di alcuni oggetti.",
	success_trade = "~g~Lo scambio è stato completato.",
	fail_trade_other_player = "~r~Lo scambio è fallito, L'altro giocatore ha abbandonato.",
	trade_other_full_item = "~r~Lo scambio è fallito, L'altro giocatore non ha abbastanza spazio.",
	trade_full_for_item = "~r~Lo scambio è fallito, Non hai abbastanza spazio.",

	press_e_to_loot_inv = "Premi ~INPUT_CONTEXT~ per lootare il suo inventario.",
	press_e_to_interact_with = "~HUD_COLOUR_NET_PLAYER27~Premi ~INPUT_CONTEXT~ per interagire con ~b~%s~HUD_COLOUR_NET_PLAYER27~.",
	press_e_to = "Premi ~INPUT_CONTEXT~ per ~b~%s~w~.",
	press_e_to_open_catalog = "Premi ~b~E~w~ per leggere il ~g~catalogo~w~.",
	this_person = "Questa persona",
	the_shop = "Questo negozzio",
	you_are_not_allowed_to_do_that = "~HUD_COLOUR_DEGEN_RED~Non hai il permesso per farlo qua.",

	no_weapon = "~r~Non hai nessuna arma equipaggiata.",
	no_need_ammo = "~r~Non hai bisogno di utilizzare le munizioni per questa armi.",
	not_right_ammo = "~r~Non stai usando le giuste munizioni, hai bisogno di ~b~%s~w~.",
	you_used_ammo = "Hai caricato ~b~%s~w~ con ~b~x%s~w~ di ~b~%s~w~.",

	choose_a_destination = "Scegli una ~b~destinazione",
	open_your_chest = "Apri la tua cassa",
	no_enough_money = "~r~Non hai abbastanza soldi.",
	you_paid = "Hai pagato ~g~$%s~w~ per ~b~%s~w~.",
	you_paid_basket = "Hai pagato ~g~$%s~w~ per il tuo cestino.",
	you_sell_basket = "Hai ricevuto ~g~$%s~w~ per aver venduto ~b~x%s~w~.",

	you_repaired_your_vehicle = "~g~Hai riparato il tuo veicolo.",
	repairing_your_vehicle = "Riparando il veicolo",
	wheels_are_fine = "~r~Le ruote del veicolo sono già a posto.",
	changing_wheel = "Cambiando la ruota",
	you_repaired_the_wheels = "~g~Hai riparato le ruote del veicolo.",

	front_post_ls = "Front post Los Santos",
	front_post_ls_2 = "Front post Los Santos 2",
	front_post_bc = "Front post Blaine County",
	front_post_bc_2 = "Front post Blaine County 2",
	main_post_ls = "Città Safe Los Santos",
	main_post_bc = "Città Safe Blaine County",
	random_zone = "Zona Casuale (Con Paracadute)",

	this_item_is_equipped = "~r~Questo item è equipaggiato, rimuovilo dai tasti rapidi.",
	only_in_safezone = "~r~Non puoi farlo al di fuori di una zona sicura.",
	-- commerce stuff
	feature_gold_only = "Questa opzione è solamente per i ~y~membri oro~w~.",
	feature_diamond_only = "Questa opzione è solamente per i ~b~membri diamante~w~.",
	you_turned_into = "Ti sei trasformato in un	 ~g~%s~w~.",
	wait_between_transformation = "~r~Perfavore aspetta un momento prima di usare la morfina nuovamente.",
	wait_between = "~r~Perfavore aspetta un momento prima di rifarlo.",
	available_morphs = "Morfina disponibile",
	animal_models = "Modelli Animali",
	zombie_models = "Modelli Zombie",
	success_update_name = "Hai cambiato il nome del tuo personaggio ~b~%s~w~.",
	success_reset_stats = "~g~Hai ripristinato correttamente le tue statistiche. (La Classifica Verrà Aggiornata a Breve)",

	-- animals
	boar = "Cinghiale",
	cat = "Gatto",
	chop = "Rottweiler (Chop)",
	rottweiler = "Rottweiler",
	cow = "Mucca",
	coyote = "Coyote",
	deer = "Cervo",
	hen = "Gallina",
	husky = "Husky",
	mtlion = "Leone",
	pig = "Maiale",
	poodle = "Barboncino",
	pug = "Carlino",
	rabbit = "Coniglio",
	rat = "Ratto",
	retriever = "Cane da riporto",
	shepherd = "Pastore",
	westy = "Westy",

	player_id = "ID del Giocatore",
	bounty = "Bounty",
	reason = "Motivo",
	id_player_not_found = "~r~Non esistono giocatori con questo di.",

	ammo_dealer = "Venditore Di Munizioni",
	misc_dealer = "Negozio Di Attrezzature",
	veh_dealer = "Venditore Di Veicoli",
	custom_dealer = "LS Custom",
	gun_dealer = "Venditore Di Armi",

	bounty_created = "Hai pagato ~g~$%s~w~ per mettere una taglia sulla testa a ~b~%s~w~.",
	contract_success = "La taglia che hai messo sulla testa a ~r~%s~w~ è stata mandata a ~b~%s~w~.",
	a_contract_on_your_head = "~r~Hai avuto una taglia sulla tua testa. Il tuo killer ha ottenuto la ricompensa.",
	reward_for_contract = "Cacciatore di taglie! Hai ottenuto una ricompensa di ~g~$%s~w~ per aver ucciso ~b~%s~w~.",

	hey_can_help_you = "Hey, come posso aiutarti?",
	i_want_to_buy_items = "Voglio comprare qualcosa",
	i_want_to_sell_items = "Voglio vendere qualcosa",

	press_context_or_jump_to_get_up = "Press ~INPUT_CONTEXT~ or ~INPUT_JUMP~ to ~b~get up~w~.",
	server_restart_warning = "Il server è in fase di riavvio..",
	auto_restart_in = "Riavvio automatico tra %s secondi.",

	not_allowed_create_character = "Non hai il permesso di creare un nuovo personaggio.",
	character_not_yours = "Questo personaggio non è tuo.",
	character_does_not_exist = "Questo personaggio non esiste o non esiste più.",
	loading_character = "Caricando il tuo personaggio...",

	playtime_is = "~b~Tempo Di Gioco Su Extinction:\n~w~%s",
	dont_spam = "^1Non Spammare!",

	babygod_warning = "~b~You left the safe-zone, you are invincible for some time find a safe place!",

	-- LS Custom
	modifications_classiques = "Classic modifications",
	modifications_custom = "Special modifications",
	modifications_benny = "Benny's modifications",
	paint = "paint",
	custom_your_car = "Custom your car",
	wheels_modifications = "Wheels modifications",
	performances = "Performances",
	neons = "Neons",
	extra = "Extra",
	klaxon = "Horn",
	teinte_fenetre = "Windows tint",
	phares_xenons = "Xenon headlights",
	modele_plaque = "Plate model",
	livery = "Livery",
	headlight_color = "Headlights color",
	wheel_type = "Wheel type",
	primary_wheel_type = "Primary wheel type",
	back_wheel_type = "Back wheel type",
	wheel_color = "Wheel color",
	tire_smoke = "Tire smoke",
	custom_color = "Custom color",
	custom_wheel = "Custom wheel",
	custom_back_wheel = "Custom back wheel",
	suspension = "Suspension",
	transmission = "Transmission",
	moteur = "Engine",
	frein = "Brake",
	turbo = "Turbo",
	primary_color = "Primary color",
	secondary_color = "Secondary color",
	interior_color = "Interior color",
	dashboard_color = "Dashboard color",
	color_effect = "Color effect",
	left_neon = "Left neon",
	right_neon = "Right neon",
	front_neon = "Front neon",
	back_neon = "Back neon",

	aileron = "Spoiler",
	pc_front = "Front bumper",
	pc_back = "Rear bumper",
	carroserie = "Side skirt",
	exhaust = "Exhaust",
	cadre = "Frame",
	calandre = "Grille",
	capot = "Hood",
	gb_left = "Left fender",
	gb_right = "Right fender",
	roof = "Roof",
	plate_support = "Plate holders",
	front_plate = "Front plate",
	interior_style = "Interior style",
	figurine = "Figurine",
	motif_dashboard = "Dashboard style",
	cadran = "Dial design",
	haut_parleur_portes = "Speaker doors",
	motif_sieges = "Seat style",
	volant = "Steering wheel",
	levier = "Shifter leavers",
	logo_custom = "Logo",
	ice = "ICE",
	haut_parleur_coffre = "Speaker back doors",
	hydrolique = "Hydraulics",
	moteur = "Engine",
	filtres_air = "Air filter",
	entretoises = "Spacers",
	arc_couverture = "Arch",
	antenne = "Antenna",
	motif_exterieur = "Exterior style",
	reservoir = "Tank",
	window = "Window",
	style = "Style",
	default = "Default",
	type = "Type",
	normal = "Normal",
	black = "Black",
	black_smoke = "Black smoke",
	simple_smoke = "Simple smole",
	stock = "Stock",
	limo = "Limousine",
	sa_black = "San Andreas black",
	sa_blue = "San Andreas blue",
	sa_white = "San Andreas white",
	simple_white = "Simple white",
	ny_white = "North Yankton white",
	race = "Race",
	sport = "Sport",
	stock = "Stock",
	street = "Street",
	discount = "Discount",
	select_your_car = "Select your car",
	select_car_custom = "Select the vehicle you want to customize. The number between arrows is the item key.",
	loading_vehicle = "Loading vehicle",
	invalid_vehicle = "~r~Invalid vehicle entity.",
	invalid_vehicle_please_spawn = "~r~Invalid vehicle item. Please spawn it one time before trying to do anything.",
	free_take_and_validate = "Everything is free. Take what you want and confirm!",
	car_custom_saved = "~g~You car modifications have been saved.",

	-- Character creation
	character_creation = "Creazione del personaggio",
	confirm = "Conferma",
	start_playing = "Inizia a giocare",
	appearance = "appearance",
	character_list = "character list",
	face_features = "face features",
	parents = "parents",
	parent = "parent",
	mix = "mix",
	skin = "skin",
	desc_mix = "Select if the shape of your face is more influenced by your father / mother.",
	desc_skin = "Select if your skin is more influenced by your father / mother.",
	identity = "identity",
	player_name = "player name",
	new_character = "new character",
	warning_headblend = "~r~You have not selected your character's parents.",
	warning_overlays = "~r~You have not selected hairs, eyebrows or beard.",
	warning_identity = "~r~Warning.~n~~w~You forgot to fill the identity tab.",

	-- kits
	kit_does_not_exist = "~r~This kit does not exist.",
	kit_needs_rank = "You do not have the ~r~%s~w~ rank.",
	wait_before_using_kit = "Please wait ~r~%s~w~ before using this kit.",
	received_kit = "You received your kit ~b~%s~w~.",
	no_kit = "You do not have any kit.",

	unable_to_find_booster = "Unable to find a booster with this id.",
	wait_already_player_boost = "Please wait a moment before using this booster. There is already one player booster active.",
	wait_already_crew_boost = "Please wait a moment before using this booster. There is already one crew booster active.",
	wait_already_server_boost = "Please wait a moment before using this booster. There is already one server booster active.",
	booster_activated = "Booster activated for ~g~%s minutes~w~! ~b~XP +%s%%",
	server_booster_activated = "~b~%s~w~ activated a server booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	crew_booster_activated = "~b~%s~w~ activated a crew booster for ~g~%s minutes~z~! ~b~XP +%s%%",
	no_booster = "You do not have any booster.",

	level_required = "You need to be level %s.",
	rank_required = "You need to have the %s rank.",
	level_required_2 = "~r~You need to be level %s.",

	-- zombie
	you_bitten = "~r~You have been bitten.",
	infection_rate = "Infection rate: ~r~%s%%",

	-- ranks
	thug = "Thug",
	hustler = "Hustler",
	soldier = "Soldier",
	trigger = "Trigger",
	enforcer = "Enforcer",
	facilitator = "Facilitator",
	public_enemy = "Public Enemy",
	shot_caller = "Shot Caller",
	street_boss = "Street Boss",
	kingpin = "Kingpin",
	-- Tattoo
	tattoo = "tattoo",
	tattoos = "tattoos",
	torso = "torso",
	head = "head",
	left_arm = "left arm",
	right_arm = "right arm",
	left_leg = "left leg",
	right_leg = "right leg",
	unknown = "unknown",
	other = "other",
	remove_tattoo = "Remove all tattoos",
	-- Hairdress
	haircuts = "Haircuts",
	makeup = "Make up",
	face = "Face",
	eyebrows = "Eyebrows",
	facial_hair = "Facial hair",
	body_hair = "Body hair",
	barber_shop = "Barber shop",
	face_makeup = "Face make up",
	lipstick = "Lipstick",
	face_foundation = "Face foundation",
	skin_blemishes = "Skin blemishes",
	skin_ageing = "Skin ageing",
	moles_freckles = "Moles & Freckles",
	sun_damage = "Skin damage",
	skin_complexion = "Skin complexion",
	body_blemishes = "Body blemishes",
	body_blemishes_2 = "Body blemishes 2",
	opacity = "Alpha",
	variations = "Variations",
	filter = "Filter",
	eyes_color = "Eyes color",
	-- Mask
	masks = "Maschera",
	-- Items
	money = "Soldi",
	-- Ammo
	["9mm"] = "9mm",
	["300_mag"] = ".300 Magnum",
	["7_62mm"] = "7.62mm",
	["calibre_12"] = "Calibre 12",
	["45_acp"] = ".45 ACP",
	["5_56mm"] = "5.56mm",
	-- Food
	["fish_1"] = "Largemouth Bass",
	["fish_2"] = "Rainbow Trout",
	["fish_3"] = "Kokanee",
	["fish_4"] = "Arctic Grayling",
	["fish_5"] = "Rock Bass",
	["fish_6"] = "Smallmouth Bass",
	["fish_7"] = "Paddlefish",
	["fish_8"] = "Bull Trout",
	["fish_9"] = "Lake Trout",
	["fish_10"] = "Chinook",
	["fish_11"] = "Pallid Sturgeon",
	["fish_12"] = "Salmone",

	misc_meat = "Raw meat",
	rabbit_meat = "Raw rabbit",
	lion_meat = "Raw lion",
	rare_plume = "Rare feather",
	dog_meat = "Raw dog",
	cat_meat = "Raw cat",
	rare_fish = "Rare fish",

	mask = "Maschera",
	malette = "Valigia",
	malette_metal = "Valigia di metallo",
	ciseaux = "Forbici",
	clean_kit = "Kit di pulizia",
	fishing_rod = "Canna da pesca",
	meuble = "Forniture",
	tissu = "Pelle",
	accessory = "Accessori",
	radio = "Radio",
	recyclor = "Recycler",
	medkit = "Medikit",
	kevlar = "Giubotto antiproiettile",
	gps = "GPS",
	repair_tool = "Kit di riparazione",
	jvn = "JVN",
	engine_veh = "Engine",
	wheel_veh = "Ruota",
	vetement = "Top",
	bloc_note = "Blocco note",
	paint_spray = "Vernice spray",
	spike = "Strisce chiodate",
	paracetamol = "Paracetamolo",
	bandage = "Benda",
	gaz_mask = "Maschera antigas",
	filter = "Filtro",
	tattoo_tool = "Strumento per tatuaggio",
	drug_med = "Drug",
	antizin = "Antizin",

	pickup_spikestrip = "Prendi strisce chiodate",
	you_dropped_spikestrip = "You dropped a ~g~strisce chiodate~w~.",
	you_pickup_spikestrip = "Hai preso da terra le ~g~strisce chiodate~w~.",

	you_have_been_killed_by = "Sei stato ucciso da ~r~%s (%s)",
	kill_notif = "~m~Ucciso",
	you_killed = "Hai ucciso ~r~%s~w~",
	already_used_reset_only = "~r~You already have reset your character.\n~w~Only %s~w~ members can redo their character more than one time.",

	hud_options = "Impostazioni HUD",
	advanced_hud = "Display advanced HUD",
	players = "Giocatori",
	health = "Vita",
	player_menu = "Menu giocatore",

	you_are_now_zombie = "~r~Sei diventato uno zombi.",

	my_weapons = "Le mie armi",
	customize_weapons = "Personalizza le mie armi",
	weapon_skin = "Skin Arma",

	-- camo
	skin_classic = "Predefinito",
	skin_green = "Verde",
	skin_yellow = "Giallo",
	skin_pink = "Rosa",
	skin_gold = "Oro",
	skin_blue = "Blu",
	skin_orange = "Arancione",
}

AddLanguage("it", my_language)
